In [7]:
import torch

In [9]:
torch.cuda.is_available() #장비연동

False

In [10]:
print(torch.__version__)

1.1.0


In [5]:
# Tensor는 NumPy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능합니다.
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3) #초기화되지 않은 5x3 행렬을 생성
print(x)

tensor([[9.2755e-39, 1.0561e-38, 7.8061e-39],
        [9.2755e-39, 8.4490e-39, 1.0102e-38],
        [9.0919e-39, 1.0102e-38, 8.9082e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38]])


In [11]:
x = torch.rand(5, 3) #무작위로 초기화된 행렬 생성
print(x)

tensor([[0.3123, 0.4153, 0.4823],
        [0.3135, 0.5100, 0.3732],
        [0.4417, 0.5439, 0.8546],
        [0.1859, 0.8025, 0.1295],
        [0.2027, 0.6560, 0.6788]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long) #dtype이 long이고 0으로 채워진 행렬을 생성합니다:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
x = torch.tensor([5.5, 3]) #데이터로부터 tensor를 직접 생성
print(x)

tensor([5.5000, 3.0000])


In [14]:
# 기존 tensor를 바탕으로 새로운 tensor를 만듭니다. 
# 이들 메소드(method)는 사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7919, -0.5498, -1.2421],
        [ 0.3681, -0.1201, -0.5750],
        [-1.1178,  1.0691, -0.2973],
        [-1.1198,  0.8967, -0.4382],
        [ 0.6261, -1.1395,  1.9857]])


In [15]:
print(x.size()) #행렬의 크기를 구합니다:

torch.Size([5, 3])


In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.6394,  0.1331, -0.7553],
        [ 0.4394, -0.1068, -0.2353],
        [-1.0786,  1.7452,  0.1648],
        [-0.6787,  1.5583, -0.0228],
        [ 1.2706, -0.8284,  2.7733]])


In [17]:
print(torch.add(x, y))

tensor([[ 1.6394,  0.1331, -0.7553],
        [ 0.4394, -0.1068, -0.2353],
        [-1.0786,  1.7452,  0.1648],
        [-0.6787,  1.5583, -0.0228],
        [ 1.2706, -0.8284,  2.7733]])


In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6394,  0.1331, -0.7553],
        [ 0.4394, -0.1068, -0.2353],
        [-1.0786,  1.7452,  0.1648],
        [-0.6787,  1.5583, -0.0228],
        [ 1.2706, -0.8284,  2.7733]])


In [19]:
y.add_(x) #덧셈: 바꿔치기(in-place) 방식. y에 x 더하기
print(y)

tensor([[ 1.6394,  0.1331, -0.7553],
        [ 0.4394, -0.1068, -0.2353],
        [-1.0786,  1.7452,  0.1648],
        [-0.6787,  1.5583, -0.0228],
        [ 1.2706, -0.8284,  2.7733]])


In [21]:
print(x)   
print(x[:, 1]) #NumPy스러운 인덱싱 표기 방법

tensor([[ 0.7919, -0.5498, -1.2421],
        [ 0.3681, -0.1201, -0.5750],
        [-1.1178,  1.0691, -0.2973],
        [-1.1198,  0.8967, -0.4382],
        [ 0.6261, -1.1395,  1.9857]])
tensor([-0.5498, -0.1201,  1.0691,  0.8967, -1.1395])


In [22]:
x = torch.randn(4, 4)
y = x.view(16) #크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
x = torch.randn(1) #만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.
print(x)
print(x.item())

tensor([1.7103])
1.71033775806427


In [25]:
a = torch.ones(5) #Torch Tensor를 NumPy 배열로 변환하기
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
import numpy as np #np (NumPy) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.
a = np.ones(5) 
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [30]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!